### ISSUE TITLE
Error with cmake on windows

### ISSUE THREAD

**Issue by RCJacH** [cfillion/reapack-index#1]
A year ago this worked and I was able to use reapack-index, until I reinstall windows due to system error.
Currently I'm getting error installin reapack-index, due to failed installation of cmake (thus rugged).

Fetching: cmake-2.8.7.gem (100%)
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing cmake:
        ERROR: Failed to build gem native extension.

    current directory: C:/Tools/Coding/Languages/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cmake-2.8.7/ext/cmake
C:/Tools/Coding/Languages/Ruby/Ruby24-x64/bin/ruby.exe -r ./siteconf20180208-2712-o1gmxu.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Tools/Coding/Languages/Ruby/Ruby24-x64/bin/$(RUBY_BASE_NAME)
extconf.rb:5:in `chdir': No such file or directory @ dir_chdir - C:/Tools/Coding/Languages/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cmake-2.8.7/vendor/cmake-2.8.7 (Errno::ENOENT)
        from extconf.rb:5:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/Tools/Coding/Languages/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cmake-2.8.7 for inspection.
Results logged to C:/Tools/Coding/Languages/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/cmake-2.8.7/gem_make.out

**Comment by cfillion** [comment]
Did you get these error by attempting to do `gem install cmake`? Otherwise that gem should not attempt to install. rugged needs the non-gem CMake: https://cmake.org/download/.

Select one of the "Add CMake to the system path ..." when installing.

**Comment by RCJacH** [comment]
Yes I did ge tthe error by attemping to do gem install cmake.
I installed the non-gem CMake, and ran gem install reapack-index, now the error is:

checking for make... no
ERROR: GNU make is required to build Rugged.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

**Comment by cfillion** [comment]
Make should have been installed as part of the Ruby post-instalation. Launch "﻿ridk install" and pick the option 3.

**Comment by RCJacH** [comment]
Thank you, it's working now after I installed msys2, although I still don't know why it was stuck since I had it installed many times.
