### ISSUE TITLE
Reapack-index doesn't warn you of missing name

### ISSUE THREAD

**Issue by myrrc** [cfillion/reapack-index#10]
Hi! While importing [this file](https://github.com/myrrc/chkld_jsfx/blob/master/index.xml) I once got an error
"The received file is invalid: invalid name".

The source of the problem was that reapack-index doesn't warn you of missing repository name (I didn't use '--no-strict'). 

Maybe you could set the '-n' parameter as mandatory?

Related to https://github.com/cfillion/reapack/pull/63

**Comment by cfillion** [comment]
reapack-index already issues a warning:

```
$ reapack-index
reapack-index
warning: This index is unnamed. Run the following command to set a name of your choice:
  reapack-index --name 'FooBar Scripts'
Indexing commit 1 of 1 (100%)...
Nothing to do!
```

**Comment by cfillion** [comment]
It should, this warning has been there since v1.0beta3 (although wording changed a bit over time):

![screenshot](https://i.imgur.com/12ZtCco.png)

**Comment by myrrc** [comment]
So I didn't manage to get the installed version to print the warning. However, re-installing the same version from RubyGems fixed the issue. Thanks.
