### ISSUE TITLE
Invalid urls generated for repository storages except for Github

### ISSUE THREAD

**Issue by myrrc** [cfillion/reapack-index#12]
E.g. given remote

```
origin  git@git.sr.ht:~myrrc/reaper-scripts (fetch)
origin  git@git.sr.ht:~myrrc/reaper-scripts (push)
```

Reapack generates files with urls like

```
https://git.sr.ht/~myrrc/reaper-scripts/raw/a306455031a3fef28a96268f8d9bbe8cd52c9579/index.xml
```

but they should be
```
https://git.sr.ht/~myrrc/reaper-scripts/blob/a306455031a3fef28a96268f8d9bbe8cd52c9579/index.xml
```

**Comment by cfillion** [comment]
Pass `--url-template='https://git.sr.ht/~myrrc/reaper-scripts/blob/$commit/$path'` to the command line or add to your .reapack-index.conf to customize the URL template. The default (auto) works with GitHub, GitLab, BitBucket etc which all use the same convention with '/raw/$commit/$path'.

**Comment by myrrc** [comment]
Ok, thanks
