### ISSUE TITLE
The --check returns 0 errors. When index.sml i created, several errors are detected

### ISSUE THREAD

**Issue by tormyvancool** [cfillion/reapack-index#16]
Here after the -- check
![image](https://github.com/user-attachments/assets/9ec9dea4-9b93-44d6-9224-8962da0bcb52)

here after the index.xml creating
![image](https://github.com/user-attachments/assets/9b00b953-857b-4803-a390-1c88d2832470)

**Comment by cfillion** [comment]
`--check` reads the repository in its current state. The normal operation mode scans the repository *through time*. That is, every commit since it was created.

Therefore, errors from the past are safe to ignore.

**Comment by tormyvancool** [comment]
> `--check` reads the repository in its current state. The normal operation mode scans the repository _through time_. That is, every commit since it was created.
> 
> Therefore, errors from the past are safe to ignore.

Uhi ... ti seems confusing. Is there  way to avoid this scan through time since what it's created is "now"?

**Comment by cfillion** [comment]
No, but it won't rescan older commits again next time (it remembers where it left off). So this just happens the very first time it's used. The purpose of that feature is adding older versions and historical context to the index.

**Comment by tormyvancool** [comment]
> No, but it won't rescan older commits again next time (it remembers where it left off). So this just happens the very first time it's used. The purpose of that feature is adding older versions and historical context to the index.
> 
> `reapack-index` always operates on the git history not the current state of the file.

Ah ok it's fine then. Thank you :-)
