### ISSUE TITLE
Problems installing CMake

### ISSUE THREAD

**Issue by TravestyAudio** [cfillion/reapack-index#4]
Hi I get the following error when trying to install reapack-index.

I followed the advice on issue #1, but I ran the latest non-gem version of CMake, and I still get the same error. I tried reinstalling both Ruby and CMake, but still get the same issue, and I have closed and reopened the command line.

Thanks.
Dave

Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing reapack-index:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rugged-0.28.3.1/ext/rugged
C:/Ruby25-x64/bin/ruby.exe -r ./siteconf20190827-7212-1xp17cf.rb extconf.rb
checking for make... yes
checking for cmake... no
ERROR: CMake is required to build Rugged.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby25-x64/bin/$(RUBY_BASE_NAME)
        --with-sha1dc
        --without-sha1dc
        --use-system-libraries

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/rugged-0.28.3.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rugged-0.28.3.1 for inspection.
Results logged to C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/rugged-0.28.3.1/gem_make.out

**Comment by cfillion** [comment]
Does running cmake from the command prompt manually work? `cmake --version` and/or `where cmake`

If not, it means cmake's directory has not been added to the system path by cmake's installer.

**Comment by TravestyAudio** [comment]
I get this

cmake --version

'cmake' is not recognized as an internal or external command,
operable program or batch file.
