### ISSUE TITLE
The created "index.xml" content is empty

### ISSUE THREAD

**Issue by zaibuyidao** [cfillion/reapack-index#5]
Hello there. My system is macOS 10.14.6, and I set up the environment according to the installation instructions. Website: https://github.com/cfillion/reapack-index/wiki

After navigating to the local git repository,
I use "reapack-index --check" and it says: "Finished checks for 0 packages with 0 failures".

At the same time, the "index.xml" created by "reapack-index --name 'FooBar Scripts'" contains empty content. Tip: Indexing commit 9 of 9 (100%) ...
Nothing to do !
Every time.

I actually have 41 lua scripts in my Repository. I re-followed the process several times and found that it was still the same. I can't find where the problem is, or which step did I miss? 

Are there more detailed steps on wiki help?

**Comment by cfillion** [comment]
Are the script files inside of subfolders? All package files must be in a folder representing the category displayed in ReaPack. Files in the repository root are not scanned by reapack-index.

**Comment by zaibuyidao** [comment]
Thank you very much. You're right, it's finally solved.
