### ISSUE TITLE
providing the same file in multiple packages results confusing conflict 

### ISSUE THREAD

**Issue by obogz** [cfillion/reapack-index#6]
Hi,

Can you please add this information
https://forum.cockos.com/showpost.php?p=2030481&postcount=658
In the packaging documentation or clarify in the error description

Example
Instead of:
warning: pack2.lua:
  'library.lua' conflicts with 'pack1.lua' -

warning: pack2.lua:
  'library.lua' conflicts with 'pack1.lua' (Only one package is allowed to own a given file in the resource directory.)

Or mention that here https://github.com/cfillion/reapack-index/wiki/Packaging-Documentation

All the best,
Bogdan

**Comment by cfillion** [comment]
Thanks for the report, I've added a paragraph to the documentation of the [`@provides`](https://github.com/cfillion/reapack-index/wiki/Packaging-Documentation#provides) tag.

**Comment by obogz** [comment]
cool, thanks!
