### ISSUE TITLE
The newly created repository raw url is invalid

### ISSUE THREAD

**Issue by zaibuyidao** [cfillion/reapack-index#7]
Hi,

I created a new repository to store my friends’ ReaScripts. I followed the instructions on the Wiki page "Getting started" and repeated the operation several times. All steps seem to be successful. The strange thing is that using the raw url is invalid (404):
https://github.com/zaibuyidao/YS_ReaScripts/raw/master/index.xml

But using this link works:
https://raw.githubusercontent.com/zaibuyidao/YS_ReaScripts/master/index.xml

I repeatedly created the repository to try to solve this problem, but still don't know where the problem is. Although the second link is valid, I hope that the first one can also be used.
Can it be solved?

Best,
Ito

**Comment by cfillion** [comment]
That repository's default branch is called `main`, not `master`. The correct link is https://github.com/zaibuyidao/YS_ReaScripts/raw/main/index.xml.
